package com.ava.mods.edgetts;

final class EdgeTtsVoices {
    static final String DEFAULT_VOICE = "en-US-AriaNeural";

    private static final String[] VOICES = {
        "en-US-AriaNeural",
        "en-US-DavisNeural",
        "en-US-GuyNeural",
        "en-US-JennyNeural",
        "en-US-AmberNeural",
        "en-US-AnaNeural",
        "en-US-AndrewNeural",
        "en-US-BrandonNeural",
        "en-US-ChristopherNeural",
        "en-US-CoraNeural",
        "en-US-ElizabethNeural",
        "en-US-MonicaNeural",
        "en-US-SaraNeural",
        "en-US-NancyNeural",
        "en-US-AshleyNeural",
        "en-US-EmmaNeural",
        "en-US-EricNeural",
        "en-US-JacobNeural",
        "en-US-MichelleNeural",
        "en-US-RogerNeural",
        "en-US-SteffanNeural",
        "en-GB-SoniaNeural",
        "en-GB-RyanNeural",
        "en-GB-LibbyNeural",
        "en-GB-MaisieNeural",
        "en-GB-ThomasNeural",
        "en-AU-NatashaNeural",
        "en-AU-WilliamNeural",
        "en-AU-AnnetteNeural",
        "en-AU-CarlyNeural",
        "en-CA-ClaraNeural",
        "en-CA-LiamNeural",
        "en-IN-NeerjaNeural",
        "en-IN-PrabhatNeural",
        "en-IE-EmilyNeural",
        "en-IE-ConnorNeural",
        "en-NZ-MollyNeural",
        "en-NZ-MitchellNeural",
        "en-ZA-LeahNeural",
        "en-ZA-LukeNeural",
        "en-PH-RosaNeural",
        "en-PH-JamesNeural",
        "en-SG-LunaNeural",
        "en-SG-WayneNeural",
        "en-HK-YanNeural",
        "en-HK-SamNeural",
        "zh-CN-XiaoxiaoNeural",
        "zh-CN-YunxiNeural",
        "zh-CN-YunyangNeural",
        "zh-CN-XiaoyiNeural",
        "zh-CN-YunjianNeural",
        "zh-CN-liaoning-XiaobeiNeural",
        "zh-CN-shaanxi-XiaoniNeural",
        "zh-HK-HiuMaanNeural",
        "zh-HK-WanLungNeural",
        "zh-TW-HsiaoChenNeural",
        "zh-TW-YunJheNeural",
        "ja-JP-NanamiNeural",
        "ja-JP-KeitaNeural",
        "ko-KR-SunHiNeural",
        "ko-KR-InJoonNeural",
        "fr-FR-DeniseNeural",
        "fr-FR-HenriNeural",
        "fr-CA-SylvieNeural",
        "fr-CA-AntoineNeural",
        "fr-CH-ArianeNeural",
        "fr-CH-GuillaumeNeural",
        "de-DE-KatjaNeural",
        "de-DE-ConradNeural",
        "de-AT-IngridNeural",
        "de-AT-JonasNeural",
        "de-CH-LeniNeural",
        "de-CH-JanNeural",
        "es-ES-ElviraNeural",
        "es-ES-AlvaroNeural",
        "es-MX-DaliaNeural",
        "es-MX-JorgeNeural",
        "es-AR-ElenaNeural",
        "es-AR-TomasNeural",
        "es-CO-SalomeNeural",
        "es-CO-GonzaloNeural",
        "es-CL-CatalinaNeural",
        "es-CL-ManuelNeural",
        "it-IT-ElsaNeural",
        "it-IT-DiegoNeural",
        "pt-BR-FranciscaNeural",
        "pt-BR-AntonioNeural",
        "pt-PT-RaquelNeural",
        "pt-PT-DuarteNeural",
        "ru-RU-SvetlanaNeural",
        "ru-RU-DmitryNeural",
        "vi-VN-HoaiMyNeural",
        "vi-VN-NamMinhNeural",
        "th-TH-PremwadeeNeural",
        "th-TH-NiwatNeural",
        "id-ID-GadisNeural",
        "id-ID-ArdiNeural",
        "hi-IN-SwaraNeural",
        "hi-IN-MadhurNeural",
        "ar-SA-ZariyahNeural",
        "ar-SA-HamedNeural",
        "ar-EG-SalmaNeural",
        "ar-EG-ShakirNeural",
        "tr-TR-EmelNeural",
        "tr-TR-AhmetNeural",
        "nl-NL-ColetteNeural",
        "nl-NL-FennaNeural",
        "pl-PL-ZofiaNeural",
        "pl-PL-MarekNeural",
        "uk-UA-PolinaNeural",
        "uk-UA-OstapNeural",
        "cs-CZ-VlastaNeural",
        "cs-CZ-AntoninNeural",
        "da-DK-ChristelNeural",
        "da-DK-JeppeNeural",
        "fi-FI-NooraNeural",
        "fi-FI-HarriNeural",
        "el-GR-AthinaNeural",
        "el-GR-NestorasNeural",
        "he-IL-HilaNeural",
        "he-IL-AvriNeural",
        "hu-HU-NoemiNeural",
        "hu-HU-TamasNeural",
        "nb-NO-PernilleNeural",
        "nb-NO-FinnNeural",
        "ro-RO-AlinaNeural",
        "ro-RO-EmilNeural",
        "sk-SK-ViktoriaNeural",
        "sk-SK-LukasNeural",
        "sv-SE-SofieNeural",
        "sv-SE-MattiasNeural",
        "bg-BG-KalinaNeural",
        "bg-BG-BorislavNeural",
        "hr-HR-GabrijelaNeural",
        "hr-HR-SreckoNeural",
        "ms-MY-YasminNeural",
        "ms-MY-OsmanNeural",
        "fil-PH-AngeloNeural",
        "fil-PH-BlessieNeural",
        "et-EE-AnuNeural",
        "et-EE-KertNeural",
        "lv-LV-EveritaNeural",
        "lv-LV-NilsNeural",
        "lt-LT-OnaNeural",
        "lt-LT-LeonasNeural",
        "ca-ES-JoanaNeural",
        "ca-ES-EnricNeural",
        "is-IS-GudrunNeural",
        "is-IS-GunnarNeural",
        "af-ZA-AdriNeural",
        "af-ZA-WillemNeural",
        "sw-TZ-RehemaNeural",
        "sw-TZ-DaudiNeural",
        "ur-PK-UzmaNeural",
        "ur-PK-AsadNeural",
        "bn-IN-BashkarNeural",
        "bn-IN-TanishaaNeural",
        "ta-IN-PallaviNeural",
        "ta-IN-ValluvarNeural",
        "te-IN-ShrutiNeural",
        "te-IN-MohanNeural",
        "mr-IN-AarohiNeural",
        "mr-IN-ManoharNeural",
        "gu-IN-NiranjanNeural",
        "gu-IN-DhwaniNeural",
        "kn-IN-SapnaNeural",
        "kn-IN-GaganNeural",
        "ml-IN-MidhunNeural",
        "ml-IN-SobhanaNeural",
        "pa-IN-OjasNeural",
        "pa-IN-NavleenNeural",
        "su-ID-TutiNeural",
        "su-ID-JajangNeural",
        "sl-SI-PetraNeural",
        "sl-SI-RokNeural",
        "az-AZ-BanuNeural",
        "az-AZ-BabekNeural",
        "sq-AL-AnilaNeural",
        "sq-AL-IlirNeural",
        "mk-MK-MarijaNeural",
        "mk-MK-AleksandarNeural",
        "sr-RS-SophieNeural",
        "sr-RS-NicholasNeural",
        "cy-GB-NiaNeural",
        "cy-GB-AledNeural",
        "ga-IE-OrlaNeural",
        "ga-IE-ColmNeural",
        "eu-ES-AinhoaNeural",
        "eu-ES-AnderNeural",
        "gl-ES-SabelaNeural",
        "gl-ES-XianNeural"
    };

    private static final String[] WYOMING_LANGUAGES = {
        "en-US", "en-GB", "en-AU", "en-CA", "en-IN", "en-IE", "en-NZ", "en-ZA",
        "en-PH", "en-SG", "en-HK",
        "zh-CN", "zh-HK", "zh-TW",
        "ja-JP", "ko-KR",
        "fr-FR", "fr-CA", "fr-CH",
        "de-DE", "de-AT", "de-CH",
        "es-ES", "es-MX", "es-AR", "es-CO", "es-CL",
        "it-IT", "pt-BR", "pt-PT", "ru-RU",
        "vi-VN", "th-TH", "id-ID", "hi-IN",
        "ar-SA", "ar-EG", "tr-TR", "nl-NL",
        "pl-PL", "uk-UA", "cs-CZ", "da-DK", "fi-FI",
        "el-GR", "he-IL", "hu-HU", "nb-NO", "ro-RO",
        "sk-SK", "sv-SE", "bg-BG", "hr-HR", "ms-MY",
        "fil-PH", "et-EE", "lv-LV", "lt-LT", "ca-ES",
        "is-IS", "af-ZA", "sw-TZ", "ur-PK", "bn-IN",
        "ta-IN", "te-IN", "mr-IN", "gu-IN", "kn-IN",
        "ml-IN", "pa-IN", "su-ID", "sl-SI", "az-AZ",
        "sq-AL", "mk-MK", "sr-RS", "cy-GB", "ga-IE",
        "eu-ES", "gl-ES"
    };

    private EdgeTtsVoices() {
    }

    static String[] voices() {
        return VOICES.clone();
    }

    static String[] wyomingLanguages() {
        return WYOMING_LANGUAGES.clone();
    }

    static String languageOf(String voice) {
        if (voice == null || voice.length() < 5) {
            return "en-US";
        }
        return voice.substring(0, 5);
    }

    static boolean isValid(String voice) {
        if (voice == null || voice.isEmpty()) {
            return false;
        }
        for (String v : VOICES) {
            if (v.equals(voice)) {
                return true;
            }
        }
        return false;
    }
}
